<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class ContactRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, mixed>
     */
    public function rules()
    {
        return [
            'name' => 'required',
            'email' => 'required|email',
            'subject' => 'required|min:5|max:50',
            'message' => 'required|min:15|max:200'
        ];
    }

    public function attributes()
    {
        return [
          'name' => 'имя'
        ];
        return parent::attributes(); // TODO: Change the autogenerated stub
    }

    public function messages()
    {
        return [
            'name.required' => 'поле имя обязательно',
            'email.required' => 'поле email обязательно',
            'email.email' => 'поле email неверное',
            'subject.required' => 'поле subject обязательно',
            'message.required' => 'поле message обязательно',
            'subject.min' => 'поле subject минимум 5',
            'message.min' => 'поле message минимум 15',
        ];
        return parent::messages(); // TODO: Change the autogenerated stub
    }

}
